Installs react facebook login, implements login with facebook into lo…
how-i-can/news pull request #89
Opened 2021-07-30 11:14 UTC by michelleann815

Completes ticket: 

https://trello.com/c/OlwXM8fa
or
https://trello.com/c/OlwXM8fa/28-add-option-for-sign-in-with-facebook

Tasks completed:
-Create an OAuth2 client with Facebook
-Get clientID from Facebook
-install and run npm react-facebook-login
-import FacebookLogin component into login component
-use the FacebookLogin code from the npm package doc

2021-08-06 19:40 UTC, reneefromhold commented on client/src/Components/Login.js
> +    console.log(response);
Remove this if there is no use outside of console/debug

2021-08-06 19:42 UTC, reneefromhold commented on client/src/Components/Login.js
> +            appId="534803271003174"
Is this specific to your account? If yes, let's make this config based in the .env file

2021-08-06 19:45 UTC, reneefromhold requested changes
Let's talk about the appId for the Facebook login. This is something I'm unfamiliar with.
This value should be .env file based. Please create a document on what other devs onboarding to perch will need to set up to work with this feature.

2021-08-17 10:57 UTC, michelleann815 commented
Can no longer use Facebook login:
https://developers.facebook.com/blog/post/2018/06/08/enforce-https-facebook-login/
https://stackoverflow.com/questions/66848225/facebook-app-localhost-force-https-problem

2021-08-17 10:57 UTC, closed without merging